# -*- coding: utf-8 -*-
import json, os

FOLDER = os.path.dirname(os.path.abspath(__file__))

def nb(cells):
    return {'cells': cells,
            'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
                         'language_info': {'name': 'python', 'version': '3.10.0'}},
            'nbformat': 4, 'nbformat_minor': 5}

def md(src):   return {'cell_type': 'markdown', 'metadata': {}, 'source': src}
def code(src): return {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': src}

def badge(f): return f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/chaosfrey-arch/news-classification-tutorial/blob/main/{f})"

def save(filename, notebook):
    with open(os.path.join(FOLDER, filename), 'w', encoding='utf-8') as f:
        json.dump(notebook, f, ensure_ascii=False, indent=1)
    print("OK: " + filename)

# ── Chapter 9 ─────────────────────────────────────────────────────────────
save("chapter09_embedding.ipynb", nb([
    md(f"# Chapter 9 -- 词向量 Embedding\n\n{badge('chapter09_embedding.ipynb')}\n\n**本章目标：** 理解 Embedding 的原理，学会用 Keras Tokenizer 把文章转换成整数序列，并掌握 padding。\n\n**预计时间：** 45 分钟\n\n> 推荐阅读：[Jay Alammar -- Illustrated Word2Vec](https://jalammar.github.io/illustrated-word2vec/)（配图极好）"),

    md("## 9.1 TF-IDF 的局限\n\nTF-IDF 很有用，但它有两个根本缺陷：\n\n1. **不懂语义**：\"good\" 和 \"great\" 在 TF-IDF 里是完全独立的两个词，没有任何关联\n2. **高维稀疏**：词汇量 50,000 个词，每篇文章向量有 50,000 维，但 99%+ 都是 0\n\n**Embedding（词嵌入）** 解决这两个问题：\n- 每个词映射到一个**低维稠密向量**（例如 128 维）\n- 语义相近的词，向量空间里距离也近\n- 这些向量是**训练中自动学习**的，不需要手工设计"),

    md("## 9.2 Word2Vec 的核心直觉\n\nWord2Vec（2013，Google）是 Embedding 的奠基性工作。\n\n核心思想：**一个词的含义，由它周围的词决定。**\n\n例如：\n- \"I bought a ___ at the store\" → 空格里大概率是名词（apple/phone/ticket）\n- \"The ___ scored a goal\" → 大概率是运动员\n\nWord2Vec 强迫模型根据上下文预测中心词（或反过来），在这个过程中，词向量自然地学到了语义。\n\n**神奇的结果：**\n```\nvec('king') - vec('man') + vec('woman') ≈ vec('queen')\nvec('Paris') - vec('France') + vec('Italy') ≈ vec('Rome')\n```\n这说明向量空间编码了真实的语义关系！"),

    code("# 直观演示：用预训练向量感受一下「相似词」\n# 注意：gensim 下载需要时间，这里用简化版本演示概念\nimport numpy as np\n\n# 手工构造一个微型「词向量空间」来演示概念\n# 真实 Embedding 有几百维，这里用 2 维方便可视化\nwords = ['football', 'soccer', 'basketball', 'tennis',\n         'economy', 'finance', 'market', 'stock',\n         'politics', 'election', 'government', 'vote']\n\n# 假设的 2D 向量（真实情况下由训练自动生成）\nvectors = np.array([\n    [0.9, 0.1],  # football\n    [0.85, 0.15], # soccer\n    [0.8, 0.2],  # basketball\n    [0.75, 0.25], # tennis\n    [0.1, 0.9],  # economy\n    [0.15, 0.85], # finance\n    [0.2, 0.8],  # market\n    [0.25, 0.75], # stock\n    [0.1, 0.1],  # politics\n    [0.15, 0.1], # election\n    [0.2, 0.15], # government\n    [0.25, 0.1], # vote\n])\n\n# 余弦相似度\ndef cosine_sim(a, b):\n    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\n# football 和各词的相似度\nfootball_vec = vectors[0]\nprint('与 \"football\" 的余弦相似度：')\nfor word, vec in zip(words, vectors):\n    sim = cosine_sim(football_vec, vec)\n    print(f'  {word:12s}: {sim:.4f}')"),

    code("import matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.family'] = 'DejaVu Sans'\n\nfig, ax = plt.subplots(figsize=(8, 6))\ncolors = ['steelblue']*4 + ['coral']*4 + ['mediumseagreen']*4\nfor i, (word, vec) in enumerate(zip(words, vectors)):\n    ax.scatter(vec[0], vec[1], color=colors[i], s=100, zorder=3)\n    ax.annotate(word, vec, fontsize=9, xytext=(5, 5), textcoords='offset points')\n\nax.set_xlabel('Dimension 1 (Sports ↔ non-Sports)')\nax.set_ylabel('Dimension 2 (Economy ↔ non-Economy)')\nax.set_title('词向量空间（示意图）：语义相近的词聚在一起', fontsize=12)\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\nprint('Sports 词聚在右上角，Economy 词聚在左上角，Politics 词在左下角')"),

    md("## 9.3 Keras Tokenizer：把词转换成整数\n\n在用神经网络之前，我们需要把文字转换成整数序列（每个整数代表词表里的一个词）。\n\nKeras 的 `Tokenizer` 帮我们做这件事：\n\n```\n文章：\"sports team wins championship\"\n   ↓  Tokenizer\n序列：[4, 12, 7, 156]   ← 每个词对应一个整数编号\n```\n\n然后 `Embedding` 层把每个整数映射到一个向量：\n\n```\n[4, 12, 7, 156]\n   ↓  Embedding 层（维度=128）\n[[0.2, -0.1, ...],    ← 词 4 的 128 维向量\n [0.8,  0.3, ...],    ← 词 12 的 128 维向量\n ...]\n```\n\n整篇文章变成一个矩阵：**序列长度 × 嵌入维度**"),

    code("import pandas as pd, numpy as np, re\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom tensorflow.keras.preprocessing.text import Tokenizer\nfrom tensorflow.keras.preprocessing.sequence import pad_sequences\n\ndef clean_text(t):\n    t = str(t).lower()\n    t = re.sub(r'http\\S+|www\\S+|https\\S+', '', t)\n    t = re.sub(r'[^a-z\\s]', ' ', t)\n    return re.sub(r'\\s+', ' ', t).strip()\n\ndf = pd.read_csv('dataset.csv').dropna(subset=['Class']).copy()\ndf['Description'] = df['Description'].fillna('')\ndf['text'] = (df['Title'] + ' ' + df['Description']).apply(clean_text)\n\nle = LabelEncoder()\ny = le.fit_transform(df['Class'])\nX_train_text, X_test_text, y_train, y_test = train_test_split(\n    df['text'].values, y, test_size=0.3, random_state=42, stratify=y)\n\nprint(f'训练集：{len(X_train_text)} 篇，测试集：{len(X_test_text)} 篇')\nprint(f'类别：{le.classes_}')"),

    code("# 建立词表，只保留最高频的 20,000 个词\nVOCAB_SIZE = 20000\nMAX_LEN    = 100   # 每篇文章截断/补齐到 100 个词\nEMBED_DIM  = 128   # 每个词用 128 维向量表示\n\ntokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token='<OOV>')\ntokenizer.fit_on_texts(X_train_text)   # 只在训练集上建立词表！\n\n# 转换为整数序列\nX_train_seq = tokenizer.texts_to_sequences(X_train_text)\nX_test_seq  = tokenizer.texts_to_sequences(X_test_text)\n\n# 打印几个例子\nprint('原始文章：', X_train_text[0][:80])\nprint('整数序列：', X_train_seq[0][:20], '...')\nprint(f'\\n词表大小：{len(tokenizer.word_index)} 个不同的词')\nprint(f'序列长度（前5篇）：{[len(s) for s in X_train_seq[:5]]}')"),

    md("## 9.4 Padding（补齐/截断）\n\n问题：每篇文章长度不同，神经网络需要固定长度的输入。\n\n解决：`pad_sequences`\n- 太短的序列：在**前面**补 0（padding）\n- 太长的序列：截断前面，保留后面（`truncating='pre'`）\n\n```\n原始：[4, 12, 7, 156]        → 只有 4 个词\n补齐：[0, 0, 0, 0, ..., 4, 12, 7, 156]  → 100 个位置\n```\n\n补 0 的位置在 Embedding 层中对应零向量，不影响学习。"),

    code("# pad_sequences：统一长度为 MAX_LEN=100\nX_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN,\n                             padding='pre', truncating='pre')\nX_test_pad  = pad_sequences(X_test_seq,  maxlen=MAX_LEN,\n                             padding='pre', truncating='pre')\n\nprint(f'Padding 后训练集形状：{X_train_pad.shape}')   # (N, 100)\nprint(f'Padding 后测试集形状：{X_test_pad.shape}')\nprint()\nprint('第一篇文章（padding 后最后 20 个位置）：')\nprint(X_train_pad[0, -20:])  # 前面是 0，后面是真实词编号"),

    code("# 文章长度分布\nimport matplotlib.pyplot as plt\nlengths = [len(s) for s in X_train_seq]\nplt.figure(figsize=(10, 4))\nplt.hist(lengths, bins=50, color='steelblue', edgecolor='white', alpha=0.8)\nplt.axvline(MAX_LEN, color='red', linewidth=2, linestyle='--', label=f'MAX_LEN={MAX_LEN}')\nplt.axvline(np.percentile(lengths, 95), color='orange', linewidth=2,\n            linestyle='--', label=f'95th percentile={int(np.percentile(lengths,95))}')\nplt.xlabel('文章词数')\nplt.ylabel('频次')\nplt.title('训练集文章长度分布')\nplt.legend()\nplt.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\nprint(f'平均长度：{np.mean(lengths):.0f} 词，最长：{max(lengths)} 词，95% 分位数：{int(np.percentile(lengths,95))} 词')"),

    md("## 9.5 Embedding 层在 Keras 里的写法\n\n```python\nfrom tensorflow.keras.layers import Embedding\n\nEmbedding(\n    input_dim=VOCAB_SIZE,   # 词表大小（20,000）\n    output_dim=EMBED_DIM,   # 每个词的向量维度（128）\n    input_length=MAX_LEN,   # 序列长度（100）\n)\n```\n\n输入：`(batch_size, 100)` — 100 个整数\n输出：`(batch_size, 100, 128)` — 100 个词，每个词 128 维向量\n\nEmbedding 层的权重（词表大小 × 嵌入维度 = 20000×128 = 2,560,000 个参数）会在训练中自动更新。\n\n**下一章** 我们将在 CNN 里实际使用这个 Embedding 层。"),

    md("## 总结\n\n| 概念 | 含义 |\n|------|------|\n| Embedding | 把整数（词编号）映射到低维稠密向量 |\n| Word2Vec | 利用上下文预测训练词向量的经典方法 |\n| Tokenizer | 建立词表，把文章转为整数序列 |\n| pad_sequences | 把变长序列统一为固定长度 |\n| VOCAB_SIZE | 词表大小（保留最高频的 N 个词）|\n| MAX_LEN | 序列截断/补齐长度 |\n| EMBED_DIM | 每个词的向量维度 |\n\n**下一章 →** Chapter 10：第三个分类器——卷积神经网络（CNN）")
]))

# ── Chapter 10 ────────────────────────────────────────────────────────────
save("chapter10_cnn.ipynb", nb([
    md(f"# Chapter 10 -- 第三个分类器：CNN\n\n{badge('chapter10_cnn.ipynb')}\n\n**本章目标：** 理解 1D 卷积在文本上的作用，搭建并训练 TextCNN，对比前面模型的结果。\n\n**预计时间：** 60 分钟\n\n> 原始论文：[Kim 2014 -- Convolutional Neural Networks for Sentence Classification](https://arxiv.org/abs/1408.5882)"),

    md("## 10.1 为什么用 CNN 处理文本？\n\nCNN（卷积神经网络）最初是为图像设计的，但在文本上也很有效。\n\n**直觉：** 文本分类中，关键信息往往是**局部短语**，而不是全文的整体结构：\n- \"scored a goal\" → Sports\n- \"stock market crash\" → Business\n- \"launched a rocket\" → Science/Tech\n\n**1D 卷积核** 就像一个滑动窗口，扫描文章里的每一段短语（n-gram），检测是否存在某种模式。\n\n类比：用放大镜扫描文章，每次看 3-5 个词，判断这段话是否包含某个主题信号。"),

    md("## 10.2 1D 卷积的工作原理\n\n```\n文章（padding 后）：[w1, w2, w3, w4, w5, ..., w100]\n每个 wi 是 128 维向量（来自 Embedding 层）\n\n卷积核大小 = 3（即每次看 3 个词）：\n  位置 1-3：[w1, w2, w3] → 一个分数（这 3 个词的「激活强度」）\n  位置 2-4：[w2, w3, w4] → 一个分数\n  ...\n  位置 98-100：[w98, w99, w100] → 一个分数\n\n结果：100-3+1 = 98 个分数，组成一个特征向量\n```\n\n**GlobalMaxPooling1D**：从 98 个分数里取最大值 → 1 个数\n- 含义：这个卷积核「检测的模式」在文章中**出现过的最强信号**\n- 不管模式出现在文章哪个位置，都能被捕获（位置不变性）"),

    md("## 10.3 多尺度卷积（Multi-scale Filters）\n\nKim 2014 论文的核心设计：**同时用多种大小的卷积核**\n\n```\nEmbedding 层输出 (100, 128)\n    ↓              ↓              ↓\nConv1D(128, 3)  Conv1D(128, 4)  Conv1D(128, 5)   ← 同时检测 3、4、5 个词的短语\n    ↓              ↓              ↓\nGlobalMaxPool  GlobalMaxPool  GlobalMaxPool\n    ↓              ↓              ↓\n [128 维]       [128 维]       [128 维]\n    └──────────────────────────────┘\n              拼接（Concatenate）\n                  [384 维]\n                     ↓\n              Dense(4, softmax)\n                  [4 个类别]\n```\n\n每种大小的卷积核捕获不同粒度的语言模式，合并后信息更丰富。"),

    code("import pandas as pd, numpy as np, re\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom tensorflow.keras.preprocessing.text import Tokenizer\nfrom tensorflow.keras.preprocessing.sequence import pad_sequences\n\ndef clean_text(t):\n    t = str(t).lower()\n    t = re.sub(r'http\\S+|www\\S+|https\\S+', '', t)\n    t = re.sub(r'[^a-z\\s]', ' ', t)\n    return re.sub(r'\\s+', ' ', t).strip()\n\ndf = pd.read_csv('dataset.csv').dropna(subset=['Class']).copy()\ndf['Description'] = df['Description'].fillna('')\ndf['text'] = (df['Title'] + ' ' + df['Description']).apply(clean_text)\n\nle = LabelEncoder()\ny = le.fit_transform(df['Class'])\nX_train_text, X_test_text, y_train, y_test = train_test_split(\n    df['text'].values, y, test_size=0.3, random_state=42, stratify=y)\n\nVOCAB_SIZE = 20000\nMAX_LEN    = 100\nEMBED_DIM  = 128\n\ntokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token='<OOV>')\ntokenizer.fit_on_texts(X_train_text)\n\nX_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train_text),\n                             maxlen=MAX_LEN, padding='pre', truncating='pre')\nX_test_pad  = pad_sequences(tokenizer.texts_to_sequences(X_test_text),\n                             maxlen=MAX_LEN, padding='pre', truncating='pre')\n\nprint('数据准备完毕！')\nprint(f'X_train_pad: {X_train_pad.shape}, X_test_pad: {X_test_pad.shape}')"),

    code("import tensorflow as tf\nfrom tensorflow.keras.models import Model\nfrom tensorflow.keras.layers import (Input, Embedding, Conv1D, GlobalMaxPooling1D,\n                                      Dense, Dropout, Concatenate)\nfrom tensorflow.keras.callbacks import EarlyStopping\nfrom tensorflow.keras.utils import to_categorical\n\ny_train_cat = to_categorical(y_train, 4)\ny_test_cat  = to_categorical(y_test,  4)\n\n# 多尺度 TextCNN（Kim 2014 风格）\nNUM_FILTERS = 128  # 每种卷积核的数量\nFILTER_SIZES = [3, 4, 5]  # 三种尺度\n\ninputs = Input(shape=(MAX_LEN,), name='input')\nemb = Embedding(VOCAB_SIZE, EMBED_DIM, name='embedding')(inputs)\n\n# 三路卷积并行\nbranches = []\nfor fs in FILTER_SIZES:\n    x = Conv1D(NUM_FILTERS, fs, activation='relu', name=f'conv_{fs}')(emb)\n    x = GlobalMaxPooling1D(name=f'pool_{fs}')(x)\n    branches.append(x)\n\nmerged = Concatenate(name='concat')(branches)     # 拼接三路特征\nx = Dropout(0.5, name='dropout')(merged)\noutputs = Dense(4, activation='softmax', name='output')(x)\n\ncnn_model = Model(inputs, outputs, name='TextCNN')\ncnn_model.compile(optimizer='adam',\n                  loss='categorical_crossentropy',\n                  metrics=['accuracy'])\ncnn_model.summary()"),

    code("early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n\nhistory = cnn_model.fit(\n    X_train_pad, y_train_cat,\n    epochs=15,\n    batch_size=256,\n    validation_split=0.1,\n    callbacks=[early_stop],\n    verbose=1\n)\nprint(f'实际训练了 {len(history.history[\"loss\"])} 轮')"),

    code("import matplotlib.pyplot as plt\nfrom sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix\nimport seaborn as sns\n\n# 训练曲线\nfig, axes = plt.subplots(1, 2, figsize=(12, 4))\nfor i, (metric, title) in enumerate([('accuracy', 'Accuracy'), ('loss', 'Loss')]):\n    axes[i].plot(history.history[metric], label='Train')\n    axes[i].plot(history.history[f'val_{metric}'], label='Validation')\n    axes[i].set_title(f'TextCNN -- {title}', fontsize=13)\n    axes[i].set_xlabel('Epoch'); axes[i].set_ylabel(title)\n    axes[i].legend(); axes[i].grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()"),

    code("# 评估\ny_pred_prob = cnn_model.predict(X_test_pad, verbose=0)\ny_pred = np.argmax(y_pred_prob, axis=1)\n\nacc = accuracy_score(y_test, y_pred)\nf1  = f1_score(y_test, y_pred, average='macro')\nprint(f'TextCNN  Accuracy: {acc:.4f}  |  Macro F1: {f1:.4f}')\nprint()\nprint(classification_report(y_test, y_pred, target_names=le.classes_))\n\n# 混淆矩阵\ncm = confusion_matrix(y_test, y_pred)\nplt.figure(figsize=(6, 5))\nsns.heatmap(cm, annot=True, fmt='d', cmap='Blues',\n            xticklabels=le.classes_, yticklabels=le.classes_)\nplt.xlabel('Predicted'); plt.ylabel('True')\nplt.title('TextCNN -- Confusion Matrix')\nplt.tight_layout()\nplt.show()"),

    code("# 保存模型和 tokenizer 供 Chapter 12 使用\nimport joblib\ncnn_model.save('cnn_model.keras')\njoblib.dump(tokenizer, 'tokenizer.pkl')\nprint('已保存：cnn_model.keras, tokenizer.pkl')"),

    md("## 总结\n\n| 概念 | 含义 |\n|------|------|\n| Conv1D(n, k) | n 个卷积核，每个看 k 个词的局部窗口 |\n| GlobalMaxPooling1D | 取序列上的最大值，输出定长向量 |\n| 多尺度卷积 | 同时用 3、4、5 个词的窗口，捕获不同粒度短语 |\n| Concatenate | 拼接多路特征 |\n| Dropout(0.5) | 训练时随机关闭 50% 的神经元，防止过拟合 |\n\n**TextCNN 预期结果：Accuracy ≈ 91-92%**（比 TF-IDF + NB 略强）\n\n**下一章 →** Chapter 11：第四个分类器——双向 LSTM（BiLSTM）")
]))

# ── Chapter 11 ────────────────────────────────────────────────────────────
save("chapter11_bilstm.ipynb", nb([
    md(f"# Chapter 11 -- 第四个分类器：双向 LSTM\n\n{badge('chapter11_bilstm.ipynb')}\n\n**本章目标：** 理解 RNN 和 LSTM 的核心思想，搭建双向 LSTM 分类器，与 CNN 对比。\n\n**预计时间：** 60 分钟\n\n> 强烈推荐：[Colah's Blog -- Understanding LSTMs](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)（最清晰的 LSTM 图解）"),

    md("## 11.1 RNN：处理序列数据的网络\n\nCNN 有个局限：它用固定大小的窗口（3-5 个词）看文本，**无法捕获长距离的依赖**。\n\n例如：\n> \"The player who joined the team last year **scored** a crucial goal.\"\n\n\"player\" 和 \"scored\" 相距很远，CNN 的小窗口可能捕获不到这种关系。\n\n**RNN（循环神经网络）** 的设计理念：按序列顺序处理，每一步都「记住」前面的信息。\n\n```\n词1 → [RNN 单元] → 隐藏状态 h1 ─┐\n词2 → [RNN 单元] ← h1           │  每个时间步都把上一步的\n词3 → [RNN 单元] ← h2           │  隐藏状态传递下去\n...                              │\n词n → [RNN 单元] → 最终输出     ─┘\n```\n\n最终的隐藏状态理论上包含了整个序列的信息。"),

    md("## 11.2 梯度消失问题与 LSTM\n\n**朴素 RNN 的问题：梯度消失（Vanishing Gradient）**\n\n反向传播时，梯度需要从最后一个时间步传回第一个。经过多次乘法，梯度越来越小，最终接近 0——早期时间步的词对训练几乎没有影响。\n\n**LSTM（Long Short-Term Memory，1997）** 解决了这个问题，引入三个「门控」机制：\n\n| 门 | 作用 |\n|----|------|\n| 遗忘门（Forget Gate）| 决定丢弃哪些过去信息 |\n| 输入门（Input Gate） | 决定记住哪些新信息 |\n| 输出门（Output Gate）| 决定输出哪些信息 |\n\n类比：你在读一篇文章，读到新段落时，你会忘记不相关的细节（遗忘门），记住新的关键信息（输入门），并决定现在要用哪些信息来理解当前内容（输出门）。\n\nLSTM 额外维护了一个**细胞状态（Cell State）**，像一条「高速公路」传递长距离信息，梯度可以直接通过它流动，不会消失。"),

    md("## 11.3 双向 LSTM（BiLSTM）\n\n单向 LSTM 只从左到右读文章，但文字的含义有时需要看**后面的词**：\n\n> \"The **bank** can guarantee deposits will eventually cover future tuition costs.\"\n> \"She sat on the **bank** of the river.\"\n\n同一个词 \"bank\"，看后面的词才知道含义（金融 vs. 河岸）。\n\n**双向 LSTM** 同时从两个方向处理序列：\n```\n→ 正向 LSTM：词1 → 词2 → ... → 词n  （捕获左到右的上下文）\n← 反向 LSTM：词n → 词n-1 → ... → 词1（捕获右到左的上下文）\n\n两个方向的输出拼接 → 每个位置有完整的双向上下文\n```"),

    code("import pandas as pd, numpy as np, re\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom tensorflow.keras.preprocessing.text import Tokenizer\nfrom tensorflow.keras.preprocessing.sequence import pad_sequences\nfrom tensorflow.keras.utils import to_categorical\n\ndef clean_text(t):\n    t = str(t).lower()\n    t = re.sub(r'http\\S+|www\\S+|https\\S+', '', t)\n    t = re.sub(r'[^a-z\\s]', ' ', t)\n    return re.sub(r'\\s+', ' ', t).strip()\n\ndf = pd.read_csv('dataset.csv').dropna(subset=['Class']).copy()\ndf['Description'] = df['Description'].fillna('')\ndf['text'] = (df['Title'] + ' ' + df['Description']).apply(clean_text)\n\nle = LabelEncoder()\ny = le.fit_transform(df['Class'])\nX_train_text, X_test_text, y_train, y_test = train_test_split(\n    df['text'].values, y, test_size=0.3, random_state=42, stratify=y)\n\nVOCAB_SIZE = 20000\nMAX_LEN    = 100\nEMBED_DIM  = 128\n\ntokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token='<OOV>')\ntokenizer.fit_on_texts(X_train_text)\n\nX_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train_text),\n                             maxlen=MAX_LEN, padding='pre', truncating='pre')\nX_test_pad  = pad_sequences(tokenizer.texts_to_sequences(X_test_text),\n                             maxlen=MAX_LEN, padding='pre', truncating='pre')\n\ny_train_cat = to_categorical(y_train, 4)\ny_test_cat  = to_categorical(y_test,  4)\nprint('数据准备完毕！')"),

    code("import tensorflow as tf\nfrom tensorflow.keras.models import Sequential\nfrom tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout\nfrom tensorflow.keras.callbacks import EarlyStopping\n\nLSTM_UNITS = 128\n\nbilstm_model = Sequential([\n    Embedding(VOCAB_SIZE, EMBED_DIM, input_length=MAX_LEN, name='embedding'),\n    Bidirectional(LSTM(LSTM_UNITS,\n                       return_sequences=False,   # 只返回最后一步的输出\n                       dropout=0.2,              # 输入 Dropout\n                       recurrent_dropout=0.2),   # 循环连接 Dropout\n                  name='bilstm'),\n    Dense(64, activation='relu', name='fc'),\n    Dropout(0.5, name='dropout'),\n    Dense(4, activation='softmax', name='output')\n], name='BiLSTM')\n\nbilstm_model.compile(optimizer='adam',\n                      loss='categorical_crossentropy',\n                      metrics=['accuracy'])\nbilstm_model.summary()\nprint(f'\\nBiLSTM 总参数量：{bilstm_model.count_params():,}')"),

    code("early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n\nhistory = bilstm_model.fit(\n    X_train_pad, y_train_cat,\n    epochs=15,\n    batch_size=256,\n    validation_split=0.1,\n    callbacks=[early_stop],\n    verbose=1\n)\nprint(f'实际训练了 {len(history.history[\"loss\"])} 轮')"),

    code("import matplotlib.pyplot as plt\nfrom sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix\nimport seaborn as sns\n\n# 训练曲线\nfig, axes = plt.subplots(1, 2, figsize=(12, 4))\nfor i, (metric, title) in enumerate([('accuracy', 'Accuracy'), ('loss', 'Loss')]):\n    axes[i].plot(history.history[metric], label='Train')\n    axes[i].plot(history.history[f'val_{metric}'], label='Validation')\n    axes[i].set_title(f'BiLSTM -- {title}', fontsize=13)\n    axes[i].set_xlabel('Epoch'); axes[i].set_ylabel(title)\n    axes[i].legend(); axes[i].grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()"),

    code("# 评估\ny_pred_prob = bilstm_model.predict(X_test_pad, verbose=0)\ny_pred = np.argmax(y_pred_prob, axis=1)\n\nacc = accuracy_score(y_test, y_pred)\nf1  = f1_score(y_test, y_pred, average='macro')\nprint(f'BiLSTM  Accuracy: {acc:.4f}  |  Macro F1: {f1:.4f}')\nprint()\nprint(classification_report(y_test, y_pred, target_names=le.classes_))\n\ncm = confusion_matrix(y_test, y_pred)\nplt.figure(figsize=(6, 5))\nsns.heatmap(cm, annot=True, fmt='d', cmap='Purples',\n            xticklabels=le.classes_, yticklabels=le.classes_)\nplt.xlabel('Predicted'); plt.ylabel('True')\nplt.title('BiLSTM -- Confusion Matrix')\nplt.tight_layout()\nplt.show()"),

    code("# 保存模型\nimport joblib\nbilstm_model.save('bilstm_model.keras')\njoblib.dump(tokenizer, 'tokenizer.pkl')  # 同一个 tokenizer\nprint('已保存：bilstm_model.keras, tokenizer.pkl')"),

    md("## CNN vs BiLSTM 对比\n\n| | TextCNN | BiLSTM |\n|---|---|---|\n| **核心机制** | 局部特征（n-gram 短语）| 全局序列上下文 |\n| **速度** | 快（卷积可并行）| 较慢（LSTM 顺序计算）|\n| **参数量** | 较少 | 较多 |\n| **优势** | 捕获关键词短语 | 理解长距离依赖 |\n| **适合场景** | 主题分类 | 情感分析、阅读理解 |\n\n对于新闻分类这种任务，**CNN 和 BiLSTM 效果相近**（都在 91-93% 左右），因为新闻类别主要由关键词决定，长距离依赖不是瓶颈。"),

    md("## 总结\n\n| 概念 | 含义 |\n|------|------|\n| RNN | 按序列处理，传递隐藏状态 |\n| 梯度消失 | 反向传播时梯度随时间步衰减到 0 |\n| LSTM | 用门控机制解决梯度消失，支持长距离记忆 |\n| 双向 LSTM | 同时从左到右和从右到左处理序列 |\n| return_sequences | False = 只取最后一步输出，True = 输出每一步 |\n\n**下一章 →** Chapter 12：汇总、保存与部署")
]))

# ── Chapter 12 ────────────────────────────────────────────────────────────
save("chapter12_summary.ipynb", nb([
    md(f"# Chapter 12 -- 汇总、保存与部署\n\n{badge('chapter12_summary.ipynb')}\n\n**本章目标：** 对比四个模型的结果，保存最终模型，封装一个可直接调用的预测函数，并展望下一步。\n\n**预计时间：** 30 分钟"),

    md("## 12.1 四个模型的方法对比\n\n在正式运行结果之前，先在概念层面回顾四个模型：\n\n| | 朴素贝叶斯 | kNN | TextCNN | BiLSTM |\n|---|---|---|---|---|\n| **特征表示** | TF-IDF | TF-IDF + SVD | Embedding | Embedding |\n| **学习机制** | 统计概率 | 距离+投票 | 局部卷积特征 | 序列循环记忆 |\n| **训练速度** | 最快（秒级）| 较慢（需降维）| 快（GPU 友好）| 慢（顺序计算）|\n| **可解释性** | 强（概率公式）| 强（找相似例子）| 弱 | 弱 |\n| **优势** | 基准线，速度快 | 直觉清晰 | 短语模式检测 | 长距离上下文 |\n\n**结论：** 对于新闻标题+摘要分类这类任务，TF-IDF + 朴素贝叶斯已经表现很好；深度学习的优势在更复杂的自然语言理解任务上更为明显。"),

    code("# 加载所有在前面章节里保存的模型和工具\nimport pandas as pd, numpy as np, re, joblib\nimport tensorflow as tf\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.metrics import accuracy_score, f1_score\nfrom tensorflow.keras.preprocessing.sequence import pad_sequences\n\ndef clean_text(t):\n    t = str(t).lower()\n    t = re.sub(r'http\\S+|www\\S+|https\\S+', '', t)\n    t = re.sub(r'[^a-z\\s]', ' ', t)\n    return re.sub(r'\\s+', ' ', t).strip()\n\n# 重建测试集（保证 random_state=42 与各章一致）\ndf = pd.read_csv('dataset.csv').dropna(subset=['Class']).copy()\ndf['Description'] = df['Description'].fillna('')\ndf['text'] = (df['Title'] + ' ' + df['Description']).apply(clean_text)\nle = LabelEncoder()\ny  = le.fit_transform(df['Class'])\n_, X_test_text, _, y_test = train_test_split(\n    df['text'].values, y, test_size=0.3, random_state=42, stratify=y)\n\n# 加载 TF-IDF 模型（Chapter 6）\nnb_model   = joblib.load('nb_model.pkl')\ntfidf_vec  = joblib.load('tfidf_vectorizer.pkl')\nX_test_tfidf = tfidf_vec.transform(X_test_text)\n\n# 加载 kNN 相关资源（Chapter 7）\nknn_model  = joblib.load('knn_model.pkl')\nsvd        = joblib.load('svd.pkl')\nnormalizer = joblib.load('normalizer.pkl')\nX_test_knn = normalizer.transform(svd.transform(X_test_tfidf))\n\n# 加载深度学习模型（Chapter 10, 11）\ntokenizer  = joblib.load('tokenizer.pkl')\ncnn_model  = tf.keras.models.load_model('cnn_model.keras')\nbilstm_model = tf.keras.models.load_model('bilstm_model.keras')\nX_test_pad = pad_sequences(\n    tokenizer.texts_to_sequences(X_test_text),\n    maxlen=100, padding='pre', truncating='pre')\n\nprint('所有模型加载完毕！')"),

    code("# 逐一评估，汇总结果\nresults = {}\n\n# 朴素贝叶斯\ny_nb  = nb_model.predict(X_test_tfidf)\nresults['Naive Bayes'] = {\n    'accuracy': accuracy_score(y_test, y_nb),\n    'macro_f1': f1_score(y_test, y_nb, average='macro')\n}\n\n# kNN\ny_knn = knn_model.predict(X_test_knn)\nresults['kNN'] = {\n    'accuracy': accuracy_score(y_test, y_knn),\n    'macro_f1': f1_score(y_test, y_knn, average='macro')\n}\n\n# TextCNN\ny_cnn = np.argmax(cnn_model.predict(X_test_pad, verbose=0), axis=1)\nresults['TextCNN'] = {\n    'accuracy': accuracy_score(y_test, y_cnn),\n    'macro_f1': f1_score(y_test, y_cnn, average='macro')\n}\n\n# BiLSTM\ny_bilstm = np.argmax(bilstm_model.predict(X_test_pad, verbose=0), axis=1)\nresults['BiLSTM'] = {\n    'accuracy': accuracy_score(y_test, y_bilstm),\n    'macro_f1': f1_score(y_test, y_bilstm, average='macro')\n}\n\nprint(f'{\"模型\":<15} {\"Accuracy\":>10} {\"Macro F1\":>10}')\nprint('-' * 38)\nfor name, m in results.items():\n    print(f'{name:<15} {m[\"accuracy\"]:>10.4f} {m[\"macro_f1\"]:>10.4f}')"),

    code("import matplotlib.pyplot as plt\n\nnames = list(results.keys())\naccs  = [results[n]['accuracy'] for n in names]\nf1s   = [results[n]['macro_f1'] for n in names]\n\nx = np.arange(len(names))\nwidth = 0.35\n\nfig, ax = plt.subplots(figsize=(10, 5))\nbars1 = ax.bar(x - width/2, accs, width, label='Accuracy',\n               color=['steelblue','coral','mediumseagreen','mediumpurple'])\nbars2 = ax.bar(x + width/2, f1s,  width, label='Macro F1',\n               color=['steelblue','coral','mediumseagreen','mediumpurple'], alpha=0.6)\n\nfor bar in bars1:\n    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.002,\n            f'{bar.get_height():.3f}', ha='center', fontsize=9)\nfor bar in bars2:\n    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.002,\n            f'{bar.get_height():.3f}', ha='center', fontsize=9)\n\nax.set_xticks(x); ax.set_xticklabels(names)\nax.set_ylim(0.75, 1.0)\nax.set_ylabel('Score')\nax.set_title('四个模型性能对比', fontsize=14)\nax.legend()\nax.grid(True, alpha=0.3, axis='y')\nplt.tight_layout()\nplt.show()"),

    md("## 12.2 封装预测函数\n\n最终目标：给任意一篇新闻文章，能自动预测它属于哪个类别。\n\n下面以朴素贝叶斯（效率最高、准确率最高的那个）为例封装一个完整的预测函数。"),

    code("# 封装一个完整的预测函数（以朴素贝叶斯为例，准确率最高且推理最快）\ndef predict_category(text, model=nb_model, vectorizer=tfidf_vec,\n                     label_encoder=le):\n    \"\"\"\n    输入：一篇新闻的标题或标题+摘要\n    输出：预测类别名称 + 各类别概率\n    \"\"\"\n    cleaned = clean_text(text)\n    vec     = vectorizer.transform([cleaned])\n    pred    = model.predict(vec)[0]\n    proba   = model.predict_proba(vec)[0]\n    return {\n        'predicted_class': label_encoder.inverse_transform([pred])[0],\n        'probabilities': dict(zip(label_encoder.classes_, proba.round(4)))\n    }\n\n# 测试几条样本\ntest_articles = [\n    \"Apple announces new iPhone with revolutionary AI chip and camera system\",\n    \"Manchester United defeats Arsenal 3-1 in Premier League clash\",\n    \"Federal Reserve raises interest rates amid inflation concerns\",\n    \"NASA's Mars rover discovers signs of ancient water in rock samples\",\n]\n\nfor article in test_articles:\n    result = predict_category(article)\n    print(f'文章：{article[:60]}...')\n    print(f'预测类别：{result[\"predicted_class\"]}')\n    probs = result['probabilities']\n    for cls, p in sorted(probs.items(), key=lambda x: -x[1]):\n        bar = '█' * int(p * 30)\n        print(f'  {cls:15s}: {bar} {p:.4f}')\n    print()"),

    code("# 也可以封装深度学习版本\ndef predict_category_deep(text, model=cnn_model, tok=tokenizer,\n                          label_encoder=le, max_len=100):\n    cleaned  = clean_text(text)\n    seq      = tok.texts_to_sequences([cleaned])\n    padded   = pad_sequences(seq, maxlen=max_len, padding='pre', truncating='pre')\n    proba    = model.predict(padded, verbose=0)[0]\n    pred_idx = np.argmax(proba)\n    return {\n        'predicted_class': label_encoder.inverse_transform([pred_idx])[0],\n        'probabilities': dict(zip(label_encoder.classes_, proba.round(4)))\n    }\n\n# 测试\narticle = \"Scientists discover a new species of dinosaur in Argentina\"\nresult = predict_category_deep(article)\nprint(f'文章：{article}')\nprint(f'CNN 预测类别：{result[\"predicted_class\"]}')\nfor cls, p in sorted(result['probabilities'].items(), key=lambda x: -x[1]):\n    print(f'  {cls:15s}: {p:.4f}')"),

    md("## 12.3 下一步可以做什么？\n\n恭喜！你已经完成了这个教程的全部内容。以下是一些进阶方向：\n\n### 提升模型性能\n- **预训练词向量**：用 GloVe 或 FastText 初始化 Embedding 层，代替随机初始化\n- **BERT / RoBERTa**：Transformer 架构的预训练模型，目前最强的文本分类方法，准确率可达 95%+\n- **数据增强**：对少数类别做同义词替换、回译等增强\n\n### 工程化部署\n- **FastAPI**：把预测函数包装成 REST API，让其他程序调用\n- **Streamlit**：做一个带界面的 Web Demo，直接粘贴文章就能看预测结果\n- **Docker**：容器化部署，随时随地运行\n\n### 延伸学习\n- [Hugging Face 课程](https://huggingface.co/learn/nlp-course)：学习 Transformer 和 BERT\n- [fast.ai](https://www.fast.ai/)：面向实践的深度学习课程\n- [Kaggle NLP 竞赛](https://www.kaggle.com/competitions?search=nlp)：用真实比赛练手"),

    md("## 全教程总结\n\n你学完了一条完整的 NLP 实验流水线：\n\n```\n原始数据（dataset.csv）\n    ↓\nChapter 1-2：用 pandas 探索数据，用 matplotlib 可视化\n    ↓\nChapter 3：文本预处理（正则清洗、划分训练/测试集）\n    ↓\nChapter 4：理解模型、训练、预测的概念\n    ↓\nChapter 5：TF-IDF 把文字变成数字\n    ↓\nChapter 6：朴素贝叶斯（Accuracy ≈ 90%）\nChapter 7：kNN + SVD 降维（Accuracy ≈ 84%）\n    ↓\nChapter 8：神经网络基础（反向传播、Keras）\nChapter 9：词向量 Embedding（Tokenizer、pad_sequences）\n    ↓\nChapter 10：TextCNN（Accuracy ≈ 91%）\nChapter 11：BiLSTM（Accuracy ≈ 91-92%）\n    ↓\nChapter 12：汇总对比、封装预测函数、部署展望\n```\n\n**恭喜完成全部教程！** 你已经掌握了从零到深度学习文本分类的完整技能栈。")
]))

print("Chapter 9-12 done")
